################################################################################

library     = "CURATEDsyncytinLibrary.fasta"
libraryDir  = "/scratch/pawsey0263/drivas/Factorem/Syncytin/data/syncytinDataBase/protein"
outDir      = "/scratch/pawsey0263/drivas/Factorem/Syncytin/data/diamondOutput"

################################################################################
