####################################################################################################

library     = "CURATEDsyncytinLibrary.fasta"
libraryDir  = "/scratch/pawsey0263/drivas/Factorem/Syncytin/data/syncytinDataBase/protein"

####################################################################################################
